=== StSergej/HW_Web_01_XML/src/hw_01_task/electric_tools.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema attributeFormDefault="qualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="power_tools" type="power_toolsType"/>

  <xs:complexType name="energyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="consumption" use="optional"/>
        <xs:attribute type="xs:string" name="Li-ion" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="powerType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="requirementn" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="turnoverType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="frequency" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="rotationType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="torgue" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="acousticType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="power" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="technical_dataType">
    <xs:sequence>
      <xs:element name="vitality">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Low"/>
            <xs:enumeration value="low"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="energyType" name="energy"/>
      <xs:element type="powerType" name="power"/>
      <xs:element type="turnoverType" name="turnover"/>
      <xs:element type="rotationType" name="rotation"/>
      <xs:element type="acousticType" name="acoustic"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="modelType">
    <xs:sequence>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Drill"/>
            <xs:enumeration value="Screw gun"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="brand">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Makita"/>
            <xs:enumeration value="Bosch"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="origin">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="China"/>
            <xs:enumeration value="Poland"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="handy">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Double-handed"/>
            <xs:enumeration value="One-handed"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="technical_dataType" name="technical_data"/>
      <xs:element name="material">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="PVC and steel"/>
            <xs:enumeration value="PVC"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="power_toolsType">
    <xs:sequence>
      <xs:element type="modelType" name="model" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== StSergej/HW_Web_01_XML/src/hw_01_task/electric_tools.xml
<?xml version="1.0" encoding="UTF-8" ?>

<power_tools xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation = "electric_tools.xsd">

    <model>
        <name>Drill</name>
        <brand>Makita</brand>
        <origin>China</origin>
        <handy>Double-handed</handy>
        <technical_data>
            <vitality>Low</vitality>
            <energy consumption = "230">Volt</energy>
            <power requirementn = "550">Watt</power>
            <turnover frequency = "0-4200">RPM</turnover>
            <rotation torgue = "65">Nm</rotation>
            <acoustic power = "98">dB</acoustic>
        </technical_data>
        <material>PVC and steel</material>
    </model>

    <model>
        <name>Screw gun</name>
        <brand>Bosch</brand>
        <origin>Poland</origin>
        <handy>One-handed</handy>
        <technical_data>
            <vitality>low</vitality>
            <energy Li-ion = "3">Ah</energy>
            <power requirementn = "18">Volt</power>
            <turnover frequency = "0-1700">RPM</turnover>
            <rotation torgue = "22">Nm</rotation>
            <acoustic power = "45" >dB</acoustic>
        </technical_data>
        <material>PVC</material>
    </model>

</power_tools>
